/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Herança;

public class Main {
 
    

    public static void main(String[] args) {
        
        Vendedor V = new Vendedor();
        
        
        Motorista M = new Motorista();
        
    }  
}
