/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ComandosLeituraGravacao;

public class App {

    public static void main(String[] args) {
   
    
     }
    
    
}
