/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {

    public static void main(String[] args) {
        
        //comentario de linha
        /* minha primeira linha de comentario 
        segunda linha de comentario */
        
        /** comentario de documentacao */
      
        System.out.println("ola mundo");
        
        
    }
}
