/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaCondicionalSe;

        import java.util.Scanner;
        
public class App {

    public static void main(String[] args) {

   int numero;
        
        Scanner leitorScanner = new Scanner(System.in);
        
        System.out.println("Digite um numero");

   numero = leitorScanner.nextInt();
   //para ler numero
        
        if(numero >= 100 && numero <= 200){

        System.out.println("o nuemro esta no intervalo");
        
        }else {
        System.out.println("numero nao esta no intervalo");
        }





}
}